# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'contoso:$(build.buildId)'
  dockerId: adventworks

steps:
- script: docker build -f Dockerfile -t $(dockerId).azurecr.io/$(imageName) .
  displayName: 'docker build'

- task: Docker@1
  displayName: 'Push an image'
  inputs:
    azureSubscriptionEndpoint: 'Build_Eng (3f56da7f-5953-4018-8ca8-e20dbfa0a7e2)'
    azureContainerRegistry: adventworks.azurecr.io
    command: 'Push an image'
    imageName: $(imageName)




